/*

*/
//==============================================================================
//------------------------------------------------------------------------------
//==============================================================================
#define D_MATCH				"a"
//------------------------------------------------------------------------------
#define DM_MATCH_ID			"a_1"
#define DM_ROUND_LIMIT		"a_2"
#define DM_TEAM_1			"a_3"
#define DM_TEAM_2			"a_4"
#define DM_START_TIME		"a_5"
//==============================================================================
#define D_MATCH_ROUNDS		"b"
//------------------------------------------------------------------------------
#define DMR_ROUND			"b_1"
#define DMR_MATCH_ID		"b_2"
#define DMR_MAP_ID			"b_3"
#define DMR_MAP_TYPE		"b_4"
#define DMR_TDM_MODE		"b_5"
#define DMR_WINNER			"b_6"
#define DMR_REASON			"b_7"
#define DMR_DEFENDER		"b_8"
#define DMR_ROUND_TIME		"b_9"
//==============================================================================
#define D_MATCH_PLAYERS		"c"
//------------------------------------------------------------------------------
#define DMP_NICK			"c_1"
#define DMP_MATCH_ID		"c_2"
#define DMP_TEAM_ID			"c_3"
#define DMP_KILLS			"c_4"
#define DMP_DEATHS			"c_5"
#define DMP_DAMAGE			"c_6"
#define DMP_PLAYED_ROUNDS	"c_7"