<?php
define("MAD_VERSION",			"test_mad_version");
define("MV_ID",					"mv_id");
define("MV_AVAILABLE",			"mv_available");
define("MV_MAJOR",				"mv_v_major");
define("MV_MINOR",				"mv_v_minor");
define("MV_RELEASE",			"mv_v_release");
define("MV_SPECIAL",			"mv_v_special");
define("MV_DOWNLOAD",			"mv_download");
define("MV_DATE",				"mv_date");
define("MV_CHANGELOG",			"mv_changelog");
//------------------------------------------------------------------------------
define("MAD_SERVERS",							"test_mad_servers");
define("MS_ID",									"ms_id");
define("MS_REMOTE_IP",							"ms_remote_ip");
define("MS_IP",									"ms_ip");
define("MS_PORT",								"ms_port");
define("MS_REGISTER",							"ms_register");
define("MS_USING_VERSION",						"ms_using_version");
define("MS_SYSTEM",								"ms_system");
define("MS_LAST_UPDATE",						"ms_last_update");
define("MS_LAST_MATCH_UPDATE",					"ms_last_match_update");
define("MS_LIST",								"ms_list");
define("MS_UPDATE_CONNECTION_WARNINGS",			"ms_p_warnings");
define("MS_MATCH_RESULTS_WARNINGS",				"ms_match_warnings");
define("MS_BLOCK",								"ms_block");
define("MS_MATCH_BLOCK_TIME", 					"ms_match_block_time");
define("MS_UPDATE_BLOCK_TIME",					"ms_update_block_time");
define("MS_ONLINE",								"ms_online");
define("MS_PRIORITY",							"ms_priority");
define("MS_SERVER_LAST_NAME",					"ms_server_last_name");
//------------------------------------------------------------------------------
define("MAD_MATCHES",			"test_mad_matches");
define("MM_ID",					"mm_id");
define("MM_MS_ID",				"mm_ms_id");
define("MM_ADD_TIME",			"mm_add_time");
define("MM_TEAM_1",				"mm_team_1");
define("MM_TEAM_2",				"mm_team_2");
define("MM_ROUND_LIMIT",		"mm_round_limit");
define("MM_ROUND_INFO",			"mm_round_info");
define("MM_PLAYERS_INFO",		"mm_players_info");
//------------------------------------------------------------------------------
define("MAD_NEW_MATCHES",		"mad_new_matches");
define("MNM_ID",				"mnm_id");
define("MNM_MS_ID",				"mnm_ms_id");
define("MNM_ADD_TIME",			"mnm_add_time");
define("MNM_TEAM_1",			"mnm_team_1");
define("MNM_TEAM_2",			"mnm_team_2");
define("MNM_JSON_DATA",			"mnm_json_data");